name: "Hello World Action"
description: "Print out the text Hello, World"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Hello World
      shell: bash
      run: echo "Hello, World!"
