name: "Hello World Action"
description: "Print out {REPO} says HelloWorld"
inputs:
  repo: 
    required: true
runs:
  using: "composite"
  steps:
    - name: Hello World
      shell: bash
      env:
        INPUT_REPO: ${{inputs.repo}}
      run: echo "$INPUT_REPO say HelloWorld!"
